/*
  Equipment.java
  Purpose: simple data holder for one row in the `equipment` table.
  I kept this class small on purpose — no framework, no annotations.
  It mirrors the columns we expect in schema.sql so the DAO stays clean.
*/
public class Equipment {

    // Primary key from SQLite (INTEGER PRIMARY KEY AUTOINCREMENT)
    private int id;

    // Display name: "Dumbbell", "Barbell", "Treadmill", etc.
    private String name;

    // Optional category/label: "Free Weight", "Machine", "Cardio"
    private String type;

    // Optional notes we might show in the UI later
    private String notes;

    /*
      Full constructor (used when we already know the id).
      I use this when reading rows back from the database.
    */
    public Equipment(int id, String name, String type, String notes) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.notes = notes;
    }

    /*
      Convenience constructor for inserts (id is auto-generated by SQLite).
      I use this in DAO.insert() before the row has an id.
    */
    public Equipment(String name, String type, String notes) {
        this(0, name, type, notes);
    }

    // ---------- Getters (used by the DAO and any table views) ----------
    public int getId() { return id; }
    public String getName() { return name; }
    public String getType() { return type; }
    public String getNotes() { return notes; }

    // ---------- Setters (kept simple so UI code can update fields) ----------
    public void setId(int id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setType(String type) { this.type = type; }
    public void setNotes(String notes) { this.notes = notes; }

    /*
      toString() is helpful during demos and quick logs.
      Example output:
      Equipment{id=3, name='Dumbbell', type='Free Weight', notes='5–50 lb set'}
    */
    @Override
    public String toString() {
        return "Equipment{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", type='" + type + '\'' +
                (notes != null && !notes.isBlank() ? ", notes='" + notes + '\'' : "") +
                '}';
    }
}
